RS_PORT = 6666
RS_HOST = "0.0.0.0"
IMAGES_PATH = "images"
CLIENT_PERIOD = 1000
CC_HOST = "0.0.0.0"
CC_PORT = 4444

APPLICATION_NAME = "frpyc"
CLIENT_TYPE = "image-client"
RECOGNIZER_TYPE = "recognizer-server"
